version: "3"

services:
  solar:
    build:
      context: $PWD
      dockerfile: backend/Dockerfile
    environment:
     DEBUG_TOKEN: "7031dd87-36c5-4494-a86a-721e82765a5c"
     DEBUG_USERNAME: "debug"
     DEBUG_PASSWORD: "testtest"
     DEBUG_SYSTEM: "test-system"
     DEBUG_AUTOINIT: "true"
     SERVER_PORT: "8080"

     SPRING_DATA_MONGODB_USERNAME: "mongo"
     SPRING_DATA_MONGODB_HOST: "mongo"
     SPRING_DATA_MONGODB_PASSWORD: "password"

     INFLUX_URL: "http://influx:8086"
     INFLUX_TOKEN: "password"

     ENVIRONMENT_JWTKEY: "yc&Mym^IC8DeGc#9Nvi32Bf&EuhZf77"

    command:  ["java","-jar","-Dspring.profiles.active=debug","solarmonitoring-app.jar"]

    ports:
      - "127.0.0.1:8050:8080"
      - "127.0.0.1:8060:8060"
  updater:
    build:
      context: $PWD
      dockerfile: updater/Dockerfile
    environment:
     SERVER_PORT: "8080"

     SPRING_DATA_MONGODB_USERNAME: "mongo"
     SPRING_DATA_MONGODB_HOST: "mongo"
     SPRING_DATA_MONGODB_PASSWORD: "password"

     INFLUX_URL: "http://influx:8086"
     INFLUX_TOKEN: "password"

    command:  ["java","-jar","-Dspring.profiles.active=debug","solarmonitoring-updater.jar"]

    ports:
      - "127.0.0.1:8051:8080"
      - "127.0.0.1:8061:8060"
