#
# Builds stage
#
FROM arm32v7/node:16.13-bullseye AS node
COPY frontend frontend
WORKDIR frontend
RUN npm install
RUN npm rebuild
RUN npm run build

#
# Build stage
#
FROM arm32v7/maven:3.6.0-jdk-11-slim AS build
WORKDIR backend
COPY backend/pom.xml pom.xml
RUN mvn dependency:go-offline
COPY backend/src src
COPY --from=node frontend/dist src/main/resources/public
RUN mvn -Dmaven.test.skip clean package

#
# Package stage
#
FROM arm32v7/openjdk:11-jre-slim
RUN mkdir /app
COPY --from=build backend/target/solarmonitoring-0.0.1-SNAPSHOT.jar /app/solarmonitoring.jar
COPY backend/src/main/resources/solar-template-selfmade-device.json /app/solar-template-selfmade-device.json
EXPOSE 8080
WORKDIR /app
ENTRYPOINT ["java","-jar","solarmonitoring.jar"]