version: "3.7"
services:
  influx:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influx"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influx-password-123!"
      DOCKER_INFLUXDB_INIT_ORG: "my-org"
      DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influx-password-123!"
    ports:
      - "127.0.0.1:8086:8086"
  #  grafana-proxy:
  #    image: cashee/grafana-proxy:latest
  #    ports:
  #      - "127.0.0.1:8080:80"
  #    environment:
  #      GRAFANA_PROXY_USE_HTTPS: "false"
  #      GRAFANA_BASE_URL: "http://grafana:3000"
  #      GRAFANA_API_KEY: "eyJrIjoiWm1iQzR5NzlqZWpFWmNwOGNveTVZR1BoaG81TzFPM0ciLCJuIjoidGVzdCIsImlkIjoxfQ=="
  #      GRAFANA_INJECT_CUSTOM_CSS: "true"
  grafana:
    image: grafana/grafana:8.2.4
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GRAFANA_BASE_URL: "http://localhost:1234"
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - "./newGrafana.yml:/etc/grafana/provisioning/datasources/sample.yaml:ro"
      - "./newDashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml:ro"
      - "./dashboards:/var/lib/grafana/dashboards"
    user: root
    entrypoint: ''
    command:
      - /bin/sh
      - -c
      - |
        # start consul agent and grafana
        set -ex
        #sed -i.bak -re 's#^;domain.*#domain = localhost#' /etc/grafana/grafana.ini
        sed -i.bak -re 's#^;root_url.*#root_url = http://0.0.0.0:3000/grafana#' /etc/grafana/grafana.ini
        sed -i.bak -re 's#^;serve_from_sub_path.*#serve_from_sub_path = true#' /etc/grafana/grafana.ini
        env | awk '/GF_|PATH/ { print "export \""$$0"\"" }' > /tmp/environ.sh
        exec su -s /bin/sh -c "set -ex; . /tmp/environ.sh; exec /run.sh" - grafana
  neo4j:
    image: neo4j:4.3.7
    environment:
      NEO4J_AUTH: "neo4j/neo4j-password-123!"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"

  influx-test:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influx"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influx-password-123!"
      DOCKER_INFLUXDB_INIT_ORG: "my-org"
      DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influx-password-123!"
    ports:
      - "127.0.0.1:8087:8086"
  neo4j-test:
    image: neo4j:4.3.7
    environment:
      NEO4J_AUTH: "neo4j/neo4j-password-123!"
    ports:
      - "127.0.0.1:7475:7474"
      - "127.0.0.1:7688:7687"