version: "3"

services:
  solar:
    build:
      context: $PWD
      dockerfile: backend/Dockerfile
    environment:
     #---- comment these line in if you want debuging systems and pusheing
     DEBUG_TOKEN: "password"
     DEBUG_USERNAME: "debug"
     DEBUG_PASSWORD: "testtest"
     #naming for test systems
     DEBUG_SYSTEM: "test-system"
     #----

     DEBUG_AUTOINIT: "true"
     SERVER_PORT: "8080"

     SPRING_DATA_MONGODB_USERNAME: "mongo"
     SPRING_DATA_MONGODB_HOST: "mongo"
     SPRING_DATA_MONGODB_PASSWORD: "password"

     FULLDOMAIN: "localhost:8080"

     INFLUX_URL: "http://influx:8086"
     INFLUX_TOKEN: "password"

     API_TOKENS_DEYE: "123456789"
     API_TOKENS_PROXY: "123456789"
     API_ENDPOINTS_AES-GCM_ENABLE: "true"

     JWT_KEY: "8Cmb0nAKx0f8H+BTXJc4xB5MwD6cxOtKXu+XrDQnUJ8="

    command:  ["java","-jar","-Dspring.profiles.active=debug","solarmonitoring-app.jar"]

    ports:
      - "127.0.0.1:8050:8080"
      - "127.0.0.1:8060:8060"
  updater:
    build:
      context: $PWD
      dockerfile: updater/Dockerfile
    environment:
     SERVER_PORT: "8080"

     SPRING_DATA_MONGODB_USERNAME: "mongo"
     SPRING_DATA_MONGODB_HOST: "mongo"
     SPRING_DATA_MONGODB_PASSWORD: "password"

     INFLUX_URL: "http://influx:8086"
     INFLUX_TOKEN: "password"

    command:  ["java","-jar","-Dspring.profiles.active=debug","solarmonitoring-updater.jar"]

    ports:
      - "127.0.0.1:8051:8080"
      - "127.0.0.1:8061:8060"
