version: "3.7"
services:
  influx:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influx"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influx-password-123!"
      DOCKER_INFLUXDB_INIT_ORG: "my-org"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influx-password-123!"
    ports:
      - "127.0.0.1:8086:8086"
  grafana:
    build:
      context: docker/grafana-app
    ports:
      - "127.0.0.1:3000:3000"
  neo4j:
    image: neo4j:4.3.7
    environment:
      NEO4J_AUTH: "neo4j/neo4j-password-123!"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"

  influx-test:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influx"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influx-password-123!"
      DOCKER_INFLUXDB_INIT_ORG: "my-org"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influx-password-123!"
    ports:
      - "127.0.0.1:8087:8086"
  neo4j-test:
    image: neo4j:4.3.7
    environment:
      NEO4J_AUTH: "neo4j/neo4j-password-123!"
    ports:
      - "127.0.0.1:7475:7474"
      - "127.0.0.1:7688:7687"
  grafana-test:
    image: grafana/grafana:8.2.4
    ports:
      - "127.0.0.1:3001:3000"
    volumes:
      - "./docker/grafana-app/grafana.ini:/etc/grafana/grafana.ini:ro"