version: "3.7"
services:
  influx:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influx"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influx-password-123!"
      DOCKER_INFLUXDB_INIT_ORG: "my-org"
      DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influx-password-123!"
    ports:
      - "127.0.0.1:8086:8086"
  grafana:
    image: grafana/grafana:8.2.4
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: "true"
      GF_AUTH_ANONYMOUS_ENABLED : "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE : "Admin"
    ports :
      - "127.0.0.1:3000:3000"
    volumes:
      -  "./newGrafana.yml:/etc/grafana/provisioning/datasources/sample.yaml:ro"
      - "./newDashboard.yml:/etc/grafana/provisioning/dashboards/default.yaml:ro"
      - "./dashboards:/var/lib/grafana/dashboards"
  neo4j:
    image: neo4j:4.3.7
    environment:
      NEO4J_AUTH: "neo4j/neo4j-password-123!"
    ports:
      - "127.0.0.1:7474:7474"
      - "127.0.0.1:7687:7687"

  influx-test:
    image: influxdb:2.0
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "influx"
      DOCKER_INFLUXDB_INIT_PASSWORD: "influx-password-123!"
      DOCKER_INFLUXDB_INIT_ORG: "my-org"
      DOCKER_INFLUXDB_INIT_BUCKET: "my-bucket"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "influx-password-123!"
    ports:
      - "127.0.0.1:8087:8086"
  neo4j-test:
    image: neo4j:4.3.7
    environment:
      NEO4J_AUTH: "neo4j/neo4j-password-123!"
    ports:
      - "127.0.0.1:7475:7474"
      - "127.0.0.1:7688:7687"