FROM grafana/grafana:8.2.4

COPY datasources.yml /etc/grafana/provisioning/datasources/datasources.yaml
COPY dashboards.yml /etc/grafana/provisioning/dashboards/dashboards.yaml
COPY dashboards /var/lib/grafana/dashboards



