
spring:
  data:
    mongodb:
      username: "mongo"
      password: "password"
  mail:
    password: "password"

management:
  server:
    port: 8062

server:
  port: 8052

api.tokens.deye: "123456789"

proxy:
  url: "http://localhost:8050"
  token: "123456789"
  timeout: 259200000
  directSystems: "67d5477516bcaa4e0ce1c5c1,"
  sync:
    amount: 30

influx:
  url: "http://localhost:8086"
  token: "password"
