
spring.data.mongodb.host: localhost
spring.data.mongodb.port: 27017
spring.data.mongodb.database: proxy
spring.data.mongodb.authentication-database: admin
spring.data.mongodb.auto-index-creation: true

management:
  server:
    port: 8060
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info,prometheus

#logging.level.root: debug


