spring:
  data:
    mongodb:
      username: "mongo"
      password: "password"
  mail:
    password: "password"
    host: localhost
    port: 1025
    username: service@localhost
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: false
          ssl.trust: mail.localhost


influx:
  url: "http://localhost:8086"
  token: "password"

management:
  server:
    port: 8061

server:
  port: 8051

monitoring:
  mail: "tost@tost-soft.de"