debug:
  token: "7031dd87-36c5-4494-a86a-721e82765a5c"
  username: "debug"
  password: "testtest"
  system: "test-system"

grafana:
  user: "admin"
  password: "admin"

spring:
  neo4j:
    authentication:
      password: "neo4j-password-123!"

influx.token: "influx-password-123!"

environment:
  jwtKey: "yc&Mym^IC8DeGc9Nvi32Bf&EuhZf77"
