
spring.data.mongodb.host: localhost
spring.data.mongodb.port: 27017
spring.data.mongodb.database: solar
spring.data.mongodb.authentication-database: admin

influx.organisation: my-org
influx.bucket: my-bucket

management.endpoints.web.exposure.include: health,info,prometheus

spring.main.allow-bean-definition-overriding=true:
