debug.token: "7031dd87-36c5-4494-a86a-721e82765a5c"

grafana:
  user: "admin"
  password: "admin"

spring:
  neo4j:
    authentication:
      password: "neo4j-password-123!"

influx.token: "influx-password-123!"