debug:
  token: "7031dd87-36c5-4494-a86a-721e82765a5c"
  username: "debug"
  password: "testtest"
  system: "test-system"
  autoinit: true

server:
  port: 8050

spring:
  data:
    mongodb:
      username: "mongo"
      password: "password"

influx:
  url: "http://localhost:8086"
  token: "password"

environment:
  jwtKey: "yc&Mym^IC8DeGc#9Nvi32Bf&EuhZf77"

#logging:
#  level:
#    root: debug
