debug:
  token: "7031dd87-36c5-4494-a86a-721e82765a5c"
  username: "debug"
  password: "testtest"
  system: "test-system"
  autoinit: true

server:
  port: 8050

api:
  tokens:
    deye: "123456789"
    proxy: "123456789"

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23litj3tztFJxvbopP
            clientSecret: b13f88b128694eb7d0d643065895689d04f9f99d
            #redirect-uri: {baseUrl}/api/login/oauth2/code/{registrationId}
            redirect-uri: "{baseUrl}/api/login/oauth2/callback"
  data:
    mongodb:
      username: "mongo"
      password: "password"

influx:
  url: "http://localhost:8086"
  token: "password"

jwt:
  key: 8Cmb0nAKx0f8H+BTXJc4xB5MwD6cxOtKXu+XrDQnUJ8=

#logging.level.root: debug
logging.level.de.tostsoft.solarmonitoring.app.exception.ApiExceptionHandler: debug
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG