apiVersion: 1

datasources:
  - name: influx
    type: influxdb
    access: proxy
    url: http://influx:8086
    user: influx
    secureJsonData:
      token: influx-password-123!
      password: influx-password-123!
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: my-bucket